### ISSUE TITLE
Provider Component Support: bastion

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-azure#27]
The [bastion component](https://github.com/codeontap/gen3/blob/1b355071065b2f60deec83409ab92c2ddeb35217/providers/shared/components/bastion/id.ftl) provides administrative access to resources hosted within the private network ( #25 ).

Most components deployed into a solution should not be accessible directly from the internet for security reasons. To ensure this most resources are only deployed with a private IP address within the virtual network. These addresses can not be routed over the internet directly, which is good from a security perspective, bad from a troubleshooting one. 

The bastion component provides administrators with a public facing endpoint ( generally SSH or RDP ) that they can access over the internet which puts them on a server hosted within the private network. From here they should be able to access the private resources deployed into the network. An AWS example of this is available [here](https://docs.aws.amazon.com/quickstart/latest/linux-bastion/overview.html) 

In AWS we deploy an Autoscaling group using the AWS linux based image. The autoscaling group has a minimum count of 0 and a maximum count of 1 allowing us to replace the instance or automatically remove it when it is not required

**Comment by RossMurr4y** [comment]
Azure has released this year their own PaaS service for this purpose called Azure Bastion. There are both pros/cons to using it at this current stage.

Pros:
- Less overhead (PaaS instead of IaaS)
- Very simplified setup
- Very simple remote access via Azure Portal to any private network computer.

Cons:
- It's in public preview, so may change and/or have limited regional availability for some time.
- This also means there is no SLA for it at this stage.
- Access appears to be performed only via the Azure portal

Because of these limitations I will at this stage follow the same approach adopted for AWS, and use linux hosts within a virtual machine scale set. Once Azure Bastion is GA we should revisit this component and utilise the PaaS service.

**Comment by RossMurr4y** [comment]
This is currently blocked.

As a part of deploying a VM scaling set, the VM needs to go to KeyVault to retrieve SSH information stored there during the Baseline components deployment. This is accomplished through baseline outputs, which have been held up due to an upgrade to the gen3 output processing. Currently the outputs of a template in Azure contain Null values where a value was not set, and the standard formatting does not like handling null values.
