### ISSUE TITLE
Provider Component Support: SPA

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-azure#60]
The [Single Page Application](https://github.com/codeontap/gen3/blob/eddbc80e93571b45861686dce7e79226f3cd6946/providers/shared/components/spa/id.ftl) component is used to represent static web application content which deployed to an object store and is made available over http 

Applications built as single page applications themselves should not require any server side processing and should run purely within the client side of the an application. 

However, if the application needs to access processing logic it can do this through client side calls. 

The CodeOnTap SPA component is broken into two sections 
- The actual application code which follows our build once and deploy many approach - this code is provided to the template engine as a zip file stored in the Registry  which on deployment is copied from the registry, unzipped and then copied to the SPA content location 
- A config file built using the standard environment/settings configuration for components. This allows for environmental contextual information to be retrieved and used in the in the application

For AWS we use S3 to host both the registry and the actual SPA content itself. While S3 can be used as an HTTP server directly it doesn't provide caching, compression or the ability to integrate with compute servies. Instead an SPA should be linked up to a  CDN #59  which will offer the SPA over HTTP/S

For Azure this will would align with 
- Azure Blob Storage within Azure Storage Accounts - Hosting the unzipped application code and the config file 

An SPA is generally given public access and storage keys are not provided to clients. Instead we need to look at SAS keys for authenticating access from the CDN to the SPA content 

https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview?toc=%2fazure%2fstorage%2fblobs%2ftoc.json

**Comment by RossMurr4y** [comment]
@roleyfoley is the intent here that this component utilises the baseline storage account resource (s3), or creates its own to keep the SPA away from other things that might be within that Storage Account?

**Comment by RossMurr4y** [comment]
I have reviewed these requirements and I propose the following MVP to get up and running fast, with the intention of revisiting the setup logic of the component as necessary.

### **Services & Resources:**

- [x] no services or resources required. 

### **Component: azure / spa**

- [ ] state file, establishing a "site" resource with attributes that point to the Storage Account in use.
- [ ] a skeleton setup macro that creates the necessary prologue/epilogue scripts that grant the CDN's access to the Blob storage (consuming the new utility functions below). 

### **Utilities:**
- [ ] New Azure bash utility functions that perform the following:
- Verifies the Blob store is accessible
- Copies files _from_ a Blob Store
- Copies files _to_ a Blob Store
- Syncs files between local and Blob storage.
- Delete directory recursively from Blob storage.

I will revisit this list as pieces are contributed.

**Comment by RossMurr4y** [comment]
@roleyfoley I have gone back to revisit the permissions on the storage account created in the baseline component. Somewhere along the lines we need to update the permissions on the storage account itself, because we applied the following permissions during baseline (alongside the following comment):

```
[#--
      storageAccount + keyVault : Retrieve NetworkACL Configuration
      Component roles will grant more explicit access to Storage + KeyVault.
      For now we just want blanket "deny-all" networkAcls.
--]
"networkRuleSet" : {
  "defaultAction": "Deny",
  "ipRules": [],
  "virtualNetworkRules" : []
}
```

I still agree that the blanket "deny-all" at the baseline level is probably the way we want to go, but I've found there's no ARM resource that we can create at a later time (say, during subnet creation on the Network component) that will allow us to update this ACL. We can fix up the permissions with an epilogue script and call to ```az storage account update ...``` but that feels a bit backwards. We can't grant the permissions at the time of creation though, as the vnet doesn't yet exist, and the vnet rules want a subnet Id to attach to - very chicken-and-egg situation.

In the same way that we made KeyVault rely on NSG permissions, do you feel that this would also be appropriate to apply to the storage account? Set the above networkRuleSet to ```"defaultAction": "Allow"``` and rely on other mechanisms to ensure security?

So I suppose I'm proposing 2 options and opening it up to see if you have further ideas:
1) Use a network component epilogue script to add permissions to the storage account for each applicable subnet.
2) Set ```"defaultAction": "Allow"``` and review our NSG settings closely.
